version: '3'

services:
  db: 
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: 'TodoWorld'
    container_name: TodoWorld
    volumes:
      - ./postgres:/var/lib/postgresql/data